# Implementation apyori alogorithm

### Author: Sunwoo Choi

### Data
reference: http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5975 sha256=be61e402e054a0fb6826c3edeb7e881f17b99c2c03dc2470d8be64bd90c119b7
  Stored in directory: /root/.cache/pip/wheels/cb/f6/e1/57973c631d27efd1a2f375bd6a83b2a616c4021f24aab84080
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
import pandas as pd
import numpy as np
from apyori import apriori

In [ ]:
df = pd.read_excel("http://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx")

In [ ]:
df

       InvoiceNo StockCode  ... CustomerID         Country
0         536365    85123A  ...    17850.0  United Kingdom
1         536365     71053  ...    17850.0  United Kingdom
2         536365    84406B  ...    17850.0  United Kingdom
3         536365    84029G  ...    17850.0  United Kingdom
4         536365    84029E  ...    17850.0  United Kingdom
...          ...       ...  ...        ...             ...
541904    581587     22613  ...    12680.0          France
541905    581587     22899  ...    12680.0          France
541906    581587     23254  ...    12680.0          France
541907    581587     23255  ...    12680.0          France
541908    581587     22138  ...    12680.0          France

[541909 rows x 8 columns]

In [ ]:
countries = df['Country'].unique()
print(countries)

['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']

In [ ]:
df_list_by_country = []
for country in countries:
  df_list_by_country.append(df[df['Country'] == country])

In [ ]:
df_list_by_country[2]

       InvoiceNo StockCode  ... CustomerID    Country
197       536389     22941  ...    12431.0  Australia
198       536389     21622  ...    12431.0  Australia
199       536389     21791  ...    12431.0  Australia
200       536389    35004C  ...    12431.0  Australia
201       536389    35004G  ...    12431.0  Australia
...          ...       ...  ...        ...        ...
497681    578459     22086  ...    12388.0  Australia
497682    578459     22340  ...    12388.0  Australia
497683    578459     22576  ...    12388.0  Australia
497684    578459     22580  ...    12388.0  Australia
497685    578459     22669  ...    12388.0  Australia

[1259 rows x 8 columns]

In [ ]:
col = 6
print(len(df_list_by_country[0]))

495478

In [ ]:
# Data preprocessing
records_all_countries = []
record_each_country = []
# I dropped the UK data because it is about half milion rows
# I was running the data including UK and it did not finish for 4 hours...
for country_idx in range(1, len(df_list_by_country)):
  for i in range(len(df_list_by_country[country_idx])):
    record_each_country.append([str(df_list_by_country[country_idx].values[i,j]) for j in range(col)])
  records_all_countries.append(record_each_country)

In [ ]:
results = []
for country_idx in range(len(records_all_countries)):
  association_rules = apriori(records_all_countries[country_idx], min_support=0.045, min_confidence=0.8)
  association_results = list(association_rules)
  results.append(association_results)

In [ ]:
def print_association(association_results):
  # reference from lab_10 notebook
  count = 0
  for item in association_results:
    # first index of the inner list
    # Contains base item and add item
    if count == 5:
      break
    count += 1
    pair = item[0] 
    items = [x for x in pair]
    print("Rule: " + items[0] + " -> " + items[1])

    #third index of the list located at 0th
    #of the third index of the inner list

    print("Confidence: " + str(item[2][0][2]))
    print("=====================================")

In [ ]:
record = []
for i in range(len(df_list_by_country[2])):
  record.append([str(df_list_by_country[2].values[i,j]) for j in range(col)])
association_rules = apriori(record, min_support=0.0045, min_confidence=1.0, min_length=3)
association_results = list(association_rules)

In [ ]:
print("The country is ",countries[2] )
print_association(association_results)

The country is  Australia
Rule: 1.65 -> 22629
Confidence: 1.0
=====================================
Rule: 22630 -> 1.65
Confidence: 1.0
=====================================
Rule: DOLLY GIRL LUNCH BOX -> 1.65
Confidence: 1.0
=====================================
Rule: SPACEBOY LUNCH BOX  -> 1.65
Confidence: 1.0
=====================================
Rule: 2010-12-01 10:03:00 -> 536389
Confidence: 1.0
=====================================

In [ ]:
record = []
for i in range(len(df_list_by_country[3])):
  record.append([str(df_list_by_country[3].values[i,j]) for j in range(col)])
association_rules = apriori(record, min_support=0.0045, min_confidence=1.0, min_length=3)
association_results = list(association_rules)

In [ ]:
print("The country is ",countries[3] )
print_association(association_results)

The country is  Netherlands
Rule: 0.72 -> 20724
Confidence: 1.0
=====================================
Rule: 22356 -> 0.72
Confidence: 1.0
=====================================
Rule: CHARLOTTE BAG PINK POLKADOT -> 0.72
Confidence: 1.0
=====================================
Rule: RED RETROSPOT CHARLOTTE BAG -> 0.72
Confidence: 1.0
=====================================
Rule: 2011-10-06 09:11:00 -> 1
Confidence: 1.0
=====================================

In [ ]:
record = []
for i in range(len(df_list_by_country[5])):
  record.append([str(df_list_by_country[5].values[i,j]) for j in range(col)])
association_rules = apriori(record, min_support=0.0045, min_confidence=1.0, min_length=3)
association_results = list(association_rules)
print("The country is ",countries[5])
print_association(association_results)

In [ ]:
record = []
for i in range(len(df_list_by_country[6])):
  record.append([str(df_list_by_country[6].values[i,j]) for j in range(col)])
association_rules = apriori(record, min_support=0.0045, min_confidence=1.0, min_length=3)
association_results = list(association_rules)
print("The country is ",countries[6])
print_association(association_results)